### ISSUE TITLE
¿Error al hacer web scraping de la web?

### ISSUE THREAD

**Issue by ferreXD** [josago97/RAE.NET#1]
Buenas!

Estuve haciendo pruebas con la API proporcionada en un proyecto de consola y a la hora de invocar los métodos me está devolviendo un error HTTP 403. Según las pruebas que he hecho esto se debe a que la web de la RAE piensa que somos una araña/bot haciendo peticiones a su URL.

Por ahora he encontrado una solución que es añadir un UserAgent conocido a la cabecera, como por ejemplo Mozilla.

También he encontrado un error al parsear la respuesta JSON del método GetWordOfTheDayAsync, basta con parsear la directamente la respuesta sin hacer substring.

Por el resto no he encontrado ningún error más.

Saludos!

**Comment by josago97** [comment]
Buenas,

Tienes razón, la API parece que ha cambiado y ahora es necesario hacer esos cambios. Muchas gracias por la ayuda, ya he publicado el paquete con una nueva versión donde se arreglan esos problemas.

Además, he actualizado las librerías y también he arreglado el problema que había con los acentos, ahora ya no se deberían ver en código hexadecimal.

Gracias por notificarme :)
